# If false any techs with spout will be ignored
useSpout: false
# Basic research addon. Gives all players basic commands to learn techs and earn points every so many seconds.
addon:
  enabled: false
  points: 1
  seconds: 60
# Default permissions and abilities for players with no technology researched.
# The permissions list are what permissions players HAVE (can be ignored if you are using another permission manager)
# The remaining settings are what players CANT do or use
default:
  permissions:
    - perm.a
    - perm.b
  cantPlace: [69, 70, 72, 76, 77]
  cantBreak:
  - 1
  - 4
  - 14
  - 15
  - 16
  - 21
  - 24
  - 48
  - 49
  - 56
  - 67
  - 73
  - 74
  - 87
  - 89
  - 121
  spout:
    cantCraft: [1, 20, 22, 24, 27, 28, 29, 33, 41,42,43,44,45,46,47,48,49,57,61,62,66,67,69,70,71,75,76,77,84,93,94,98,101,102,108,109,112,113,114,116,117,118]