author: croxis
database: true
description: A permission plugin where user permissions are granted based on technology
  the user has researched. An external plugin is required to grant techs.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.croxis.plugins.research.Research
name: Research
startup: postworld
version: '3.0'
commands:
  research:
    description: technology tree
    permission: research.admin
    useage: /<command> [player] or /<command> reload
permissions:
  research:
    description: Activates research for that user
    default: true
  research.logininfo:
    description: Shows research info when a player logs in
    default: true
  research.admin:
    description: Access to admin settings
    default: op
